### ISSUE TITLE
Settings not loading

### ISSUE THREAD

**Issue by StingrayNine** [BoltManGuy/UI_Scaler#3]
As the title says, the mod doesn't actually load the settings of things when in overkill mode.
The mod saves its settings fine and the JSON file is updated, but when reloading the game the panels are non-responsive and on the non-overkill setting, if they're still in the list.
The one I've been testing with (as to not lose a ton of work) is the "snow.gui.fsm.startmenu.GuiStartMenu".
When adding the panel, it responds as expected. If I save the settings and reload the game, the panel is still in the overkill list but you cannot touch it anymore without re-adding it.
Tried with 2.5, 2.6 and 2.7. Settings attached if you need them. 
[UI_Scaler JSON.zip](https://github.com/BoltManGuy/UI_Scaler/files/8032940/UI_Scaler.zip)

**Comment by Bolt-Scripts** [comment]
I honestly have no idea what's going on with that, something about changing some stuff around in the local scope refactor.
it makes no sense but whatver, it's fixed when using proper module stuff I guess so this issue shouldnt exist anymore
